[versions]
kotlinx-coroutines = "1.6.4"

stately = "1.2.5"

kotest = "5.5.5"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

stately-isoCollections = { module = "co.touchlab:stately-iso-collections", version.ref = "stately" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }