[versions]
kotlin = "1.8.21"

dokka = "1.8.10"
mavenPublish = "0.20.0"

kotlinx-coroutines = "1.6.4"

stately = "1.2.5"

okio = "3.3.0"

kotest = "5.6.1"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

stately-isoCollections = { module = "co.touchlab:stately-iso-collections", version.ref = "stately" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-nodeFilesystem = { module = "com.squareup.okio:okio-nodefilesystem", version.ref = "okio" }
okio-fakeFilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }