name: Publish Snapshot

on:
  push:
    branches:
      - main

concurrency:
  group: "release"
  cancel-in-progress: false

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}

jobs:
  publish-snapshot:
    name: Publish Snapshot

    runs-on: macOS-latest
    if: github.repository == 'MayakaApps/Kache'

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Extract Kache and Kotlin versions
        run: |
          echo "KACHE_VERSION=$(sed -rn 's/^VERSION_NAME=(.*)\r?$/\1/p' 'gradle.properties')" >> $GITHUB_ENV
          echo "KOTLIN_VERSION=$(sed -rn 's/^kotlin[[:space:]]?=[[:space:]]?\"(.*)\"/\1/p' 'gradle/libs.versions.toml')" >> $GITHUB_ENV

      - name: Restore Konan cache
        if: endsWith(env.KACHE_VERSION, '-SNAPSHOT')
        uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ env.KOTLIN_VERSION }}

      - name: Publish
        run: ./gradlew publishAllPublicationsToMavenCentralRepository

      - name: Save Konan cache
        if: endsWith(env.KACHE_VERSION, '-SNAPSHOT')
        uses: actions/cache/save@v3
        with:
          path: ~/.konan
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
